# docker-compose.yml
version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
#    networks:
#      - main
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
  grafana:
    network_mode: bridge
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#      - "localhost:127.0.0.1"
    links:
      - clickhouse1
    image: grafana/grafana:latest
#    networks:
#      - main
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=illchangeitanyway
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
  app:
    container_name: app
    entrypoint: ["npm", "run", "start"]
    depends_on:
      - prometheus
      - grafana
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9200:9200'
#    networks:
#      - main
    env_file:
      - .env
  clickhouse1:
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:127.0.0.1"
    image: clickhouse/clickhouse-server:22.8.1
    ports:
      - "8123:8123"
      - "9000:9000"
    expose:
      - "9000" # client port
      - "8123" # client port
    volumes:
      #- clickhouse_storage:/var/lib/clickhouse
      - \\wsl$$\Ubuntu\clickhouse_data\data:/var/lib/clickhouse
      - \\wsl$$\Ubuntu\clickhouse_data\log:/var/log/clickhouse-server
#    networks:
#      - main
    network_mode: bridge

volumes:
  #clickhouse_storage: {}
  prometheus_data: {}
  grafana_data: {}
  app_data: {}

#networks:
#  main:
#    enable_ipv6: false
#    driver: bridge

