version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    networks:
      - atr-net
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
  grafana:
    network_mode: bridge
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#      - "localhost:127.0.0.1"
    links:
      - clickhouse
    image: grafana/grafana:latest
    networks:
      - atr-net
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=illchangeitanyway
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
  app:
    container_name: app
    entrypoint: ["npm", "run", "start:ms:atr"]
    depends_on:
      - prometheus
      - grafana
      - clickhouse
    build:
      context: .
      dockerfile: docker/ms-app/Dockerfile
    ports:
      - '9200:9200'
    networks:
      - atr-net
    env_file:
      - .env
  app_cron:
    container_name: app_cron
    entrypoint: [ "npm", "run", "start:ms:cron" ]
    depends_on:
      - redis
      - clickhouse
    #      - grafana2
    build:
      context: .
      dockerfile: docker/ms-cron/Dockerfile
    ports:
      - '9201:9201'
    networks:
      - atr-net
    env_file:
      - .env
    network_mode: bridge
  clickhouse:
    container_name: clickhouse
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:127.0.0.1"
    image: clickhouse/clickhouse-server:22.8.1
    ports:
      - "8123:8123"
      - "9000:9000"
    expose:
      - "9000" # client port
      - "8123"
    volumes:
      #- clickhouse_storage:/var/lib/clickhouse
      - \\wsl$$\Ubuntu\clickhouse_data\data:/var/lib/clickhouse
      - \\wsl$$\Ubuntu\clickhouse_data\log:/var/log/clickhouse-server
    networks:
      - atr-net
    network_mode: bridge

volumes:
  #clickhouse_storage: {}
  prometheus_data: {}
  grafana_data: {}
  app_data: {}
networks:
  atr-net:
    driver: bridge
