version: '3.7'

services:
  redis:
    container_name: redis
    env_file:
      - .env
    image: redis:7.0.4-alpine
    network_mode: bridge
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel debug --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data

#  grafana2:
#    network_mode: bridge
#    #    extra_hosts:
#    #      - "host.docker.internal:host-gateway"
#    #      - "localhost:127.0.0.1"
#    links:
#      - clickhouse2
#    image: grafana/grafana:latest
#    #    networks:
#    #      - main
#    volumes:
#      - grafana_data:/var/lib/grafana
#      - ./grafana/provisioning:/etc/grafana/provisioning
#      - ./grafana/config.ini:/etc/grafana/config.ini
#      - ./grafana/dashboards:/var/lib/grafana/dashboards
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=illchangeitanyway
#    ports:
#      - '3000:3000'

  app_cron:
    container_name: app_cron
    networks:
      - atr-net
    entrypoint: [ "npm", "run", "start:ms:cron" ]
    depends_on:
#      - redis
      - clickhouse
#      - grafana2
    build:
      context: .
      dockerfile: docker/ms-cron/Dockerfile
    ports:
      - '9201:9201'
    env_file:
      - .env
  clickhouse:
    container_name: clickhouse
    restart: always
    networks:
      - atr-net
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#      - "localhost:127.0.0.1"
    image: clickhouse/clickhouse-server:22.8.1
    ports:
      - "8123:8123"
      - "9000:9000"
    expose:
      - "9000" # client port
      - "8123" # client port
    volumes:
      #- clickhouse_storage:/var/lib/clickhouse
      - \\wsl$$\Ubuntu\clickhouse_data\data:/var/lib/clickhouse
      - \\wsl$$\Ubuntu\clickhouse_data\log:/var/log/clickhouse-server
volumes:
  #clickhouse_storage: {}
  redis_data: {}
  grafana_data: {}
  app_cron_data: {}
networks:
  atr-net:
    driver: bridge
