# docker-compose.yml
version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    networks:
      - nesjs-network
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana:latest
    networks:
      - nesjs-network
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=illchangeitanyway
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
  app:
    container_name: app
    entrypoint: ["npm", "run", "start"]
    depends_on:
      - prometheus
      - grafana
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9200:9200'
    networks:
      - nesjs-network
    env_file:
      - .env

volumes:
  prometheus_data: {}
  grafana_data: {}
  app_data: {}

networks:
  nesjs-network:
