name: Outdated Version Action

on:
  pull_request:
    types: [opened, edited]

jobs:
  outdated-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        working-directory: packages/backend/
        run: yarn --ignore-engines
      - name: outdated version
        uses: ycjcl868/outdated-version-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: packages/backend/