name: main
on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --prod --frozen-lockfile --silent --non-interactive
          working-directory: |
            packages/backend/
            
