name: yarn-workflow
on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
        with:
          #run: yarn test
          install-command: yarn install --prod --frozen-lockfile --non-interactive
          working-directory: |
            packages/backend/
      - name: Test
        run: npm run test
            
